# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='showtimes',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='movie',
            name='run_time',
            field=models.CharField(default=b'PT00H00M', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmsId',
            field=models.CharField(default=b'MV000000000000', max_length=15),
        ),
    ]
