# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170712_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_raw', models.CharField(max_length=16)),
                ('theater_raw', models.CharField(max_length=50)),
                ('ticketURI', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='theatre',
        ),
        migrations.AddField(
            model_name='movie',
            name='showtimes_raw',
            field=models.CharField(default=b'0', max_length=1000000),
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Movie'),
        ),
    ]
