# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20170712_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_raw', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ratings_code',
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings_raw',
            field=models.CharField(default=b'NR', max_length=10),
        ),
    ]
