# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20170712_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='ticketURI',
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratings_raw',
            field=models.CharField(default=b'NR', max_length=1000),
        ),
    ]
